# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrackeruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
