# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTrackerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('project', models.CharField(max_length=250)),
                ('component', models.CharField(max_length=250)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
